import type { ScanCounts } from "@input/pen-test";
import type { CacheId } from "./caches";
import { AUDIT_OPS, isStructuralOp, type AuditOp } from "./ops";
import type { AuditCell, AuditRow } from "./run";

/** The plan's decision rule, at this size. */
export const DECISION_SIZE = 10_000;
export const INPUT_BUDGET_MS = 1;
export const STRUCTURAL_BUDGET_MS = 4;
/** A naive cost within this factor of its budget, either side, is reported as close. */
const CLOSE_FACTOR = 2;

export const CACHE_NAMES: Readonly<Record<CacheId, string>> = {
	A: "Document index (preorder, child index, parent index)",
	B: "Change-summary block index and touched-id scoping",
	C: "Block notifier list slice and segments",
	D: "Scoped decoration sources and collector merge",
	E: "AI suggestion indexes",
	F: "Search scoped rescans",
	G: "Normalization pass index",
	H: "Overlay range and inline-facts caches",
};

export const CACHE_NAIVE: Readonly<Record<CacheId, string>> = {
	A: "`documentState.rebuild()` on every commit",
	B: "block index rebuilt from the document, text lengths included, on every commit",
	C: "every touched sibling list re-walked whole (`getListItemSemantics` per run) and re-segmented with `getListSegments`",
	D: "collector refresh with `{ kind: \"full\" }` on every commit (every source over every block)",
	E: "`SuggestionListIndex.refreshAll` (the `readAllSuggestions` walk) on every commit",
	F: "`SearchController.recompute()` (full rescan) on every commit with the active query",
	G: "pass index dropped before every normalization pass",
	H: "a fresh selection contributor per paint",
};

export type Decision = "keep" | "remove";

export interface CacheDecision {
	readonly cache: CacheId;
	readonly decision: Decision;
	/** The row whose naive cost is largest relative to its budget. */
	readonly worstRow: AuditRow;
	readonly worstNaiveMs: number;
	readonly worstNaiveMinMs: number;
	readonly budgetMs: number;
	readonly close: boolean;
}

function isAuditOp(row: AuditRow): row is AuditOp {
	return (AUDIT_OPS as readonly string[]).includes(row);
}

function budgetFor(row: AuditRow): number {
	return isAuditOp(row) && isStructuralOp(row) ? STRUCTURAL_BUDGET_MS : INPUT_BUDGET_MS;
}

/**
 * Keep when, at 10k blocks, the naive consumer costs more than 1 ms on a
 * keystroke or caret move (every overlay paint counts as one) or more than
 * 4 ms on a structural commit. Cost is the naive component median: the time
 * the naive recompute itself takes on that operation.
 */
export function decide(cells: readonly AuditCell[]): CacheDecision[] {
	const decisions: CacheDecision[] = [];
	const caches = [...new Set(cells.map((cell) => cell.cache))];
	for (const cache of caches) {
		const rows = cells.filter((cell) => cell.cache === cache && cell.size === DECISION_SIZE);
		if (rows.length === 0) continue;
		let worst = rows[0] as AuditCell;
		for (const cell of rows) {
			const ratio = cell.naive.componentMedian / budgetFor(cell.row);
			if (ratio > worst.naive.componentMedian / budgetFor(worst.row)) worst = cell;
		}
		const budgetMs = budgetFor(worst.row);
		const ratio = worst.naive.componentMedian / budgetMs;
		decisions.push({
			cache,
			decision: ratio > 1 ? "keep" : "remove",
			worstRow: worst.row,
			worstNaiveMs: worst.naive.componentMedian,
			worstNaiveMinMs: worst.naive.componentMin,
			budgetMs,
			close: ratio >= 1 / CLOSE_FACTOR && ratio < CLOSE_FACTOR,
		});
	}
	return decisions;
}

function ms(value: number): string {
	return value >= 100 ? value.toFixed(0) : value >= 10 ? value.toFixed(1) : value.toFixed(2);
}

function pair(min: number, median: number): string {
	return `${ms(min)} / ${ms(median)}`;
}

function counts(value: ScanCounts): string {
	return `${value.blocksMapReads} / ${value.orderArrayReads} / ${value.textFullReads} / ${value.blockOrderReads + value.blocksMapIterations}`;
}

function size(value: number): string {
	return value >= 1000 ? `${value / 1000}k` : String(value);
}

export interface ReportContext {
	readonly date: string;
	readonly machine: string;
	readonly runs: number;
	readonly loadBefore: string;
	readonly loadAfter: string;
	readonly notes: Readonly<Partial<Record<CacheId, string>>>;
	readonly findings: readonly string[];
}

/** CACHE-AUDIT.md: method, the decision table, then every cell per cache. */
export function renderCacheAudit(cells: readonly AuditCell[], context: ReportContext): string {
	const decisions = decide(cells);
	const lines: string[] = [
		"# Cache audit (simplification plan, Phase 1)",
		"",
		"Generated by `pnpm --filter @input/pen-bench run bench:caches`; do not edit by hand.",
		"",
		`- Date: ${context.date}`,
		`- Machine: ${context.machine} (shared; load average ${context.loadBefore} before, ${context.loadAfter} after)`,
		`- Runs: ${context.runs} timed runs per mode per cell after 3 warm-up runs; incremental and naive interleaved in one process, alternating which goes first`,
		"- Fixture: `generateMixedBlockSpecs` + `mixedFixtureOps` at each size, on the realistic stack (undo, tools, delta stream, `aiExtension` with 8 staged suggestions, `searchExtension` with an open query matching one block) and a block notifier subscribed to every root block, the document and the root list (a renderer without virtualization).",
		"- Ops: keystroke = `splice-text` of one character plus the caret write; caret move = `selectText` one offset left or right; insert-block / delete-block = a paragraph in the middle; move-block = the middle item of a numbered run out and back; split = `applySplitBlock` at the end of a middle paragraph.",
		"- Op ms is the whole operation (apply, commit dispatch, every listener). Component ms is the time inside the cache's consumer only (the incremental update, or the naive recompute that replaces it). min / median.",
		"- Counts (scan probe, one counted op after one warm op, per mode): blocksMapReads / orderArrayReads / textFullReads / scanned (blockOrderReads + blocksMapIterations).",
		`- Decision rule: keep when, at ${size(DECISION_SIZE)} blocks, the naive component median exceeds ${INPUT_BUDGET_MS} ms on a keystroke or caret move (each overlay paint counts as one) or ${STRUCTURAL_BUDGET_MS} ms on a structural commit; otherwise remove. "Close" means within a factor of ${CLOSE_FACTOR} of the budget.`,
		"",
		"## Decisions",
		"",
		`| Cache | Naive recompute | Worst row at ${size(DECISION_SIZE)} | Naive ms min / median | Budget ms | Decision |`,
		"|---|---|---|---|---|---|",
	];
	for (const decision of decisions) {
		const verdict = `**${decision.decision}**${decision.close ? " (close to threshold)" : ""}`;
		lines.push(
			`| ${decision.cache}. ${CACHE_NAMES[decision.cache]} | ${CACHE_NAIVE[decision.cache]} | ${decision.worstRow} | ${pair(decision.worstNaiveMinMs, decision.worstNaiveMs)} | ${decision.budgetMs} | ${verdict} |`,
		);
	}
	if (context.findings.length > 0) {
		lines.push("", "## Reading the numbers", "", ...context.findings.map((finding) => `- ${finding}`));
	}
	const caches = [...new Set(cells.map((cell) => cell.cache))];
	for (const cache of caches) {
		lines.push("", `## ${cache}. ${CACHE_NAMES[cache]}`, "", `Naive: ${CACHE_NAIVE[cache]}.`);
		const note = context.notes[cache];
		if (note) lines.push("", note);
		lines.push(
			"",
			"| Size | Op | Op ms incr | Op ms naive | Component ms incr | Component ms naive | Counts incr | Counts naive |",
			"|---|---|---|---|---|---|---|---|",
		);
		for (const cell of cells.filter((entry) => entry.cache === cache)) {
			lines.push(
				`| ${size(cell.size)} | ${cell.row} | ${pair(cell.incremental.opMin, cell.incremental.opMedian)} | ${pair(cell.naive.opMin, cell.naive.opMedian)} | ${pair(cell.incremental.componentMin, cell.incremental.componentMedian)} | ${pair(cell.naive.componentMin, cell.naive.componentMedian)} | ${counts(cell.incremental.counts)} | ${counts(cell.naive.counts)} |`,
			);
		}
	}
	return `${lines.join("\n")}\n`;
}
